server:
  port: 8080

---

spring:

  messages:
    basename: i18n/messages

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      schemas: public
      createSchemas: true
      locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

  flyway:
    enabled: true

  springdoc:
    api-docs:
      enable: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui,html