server:
  port: 8080

---

spring:
  messages:
    basename: i18n/messages

  datasource:
    url: jdbc:postgresql://${DB_HOST_PROD}/${DB_NAME_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: ${DB_USERNAME_PROD}
      password: ${DB_PASSWORD_PROD}
      schemas: public
      createSchemas: true
      locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

  flyway:
    enabled: true

  springdoc:
    api-docs:
      enable: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui.html  # Fix the typo here

swagger:
  schemes:
    - https  # Add this property to specify HTTPS
