server:
  port: 8080

---

spring:

  message:
    basename: i18n/messages

  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:49115/railway
    username: postgres
    password: f*Aa-c1GBe4e+gbGB3FFDg*aFd+cADC-
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: postgres
      password: f*Aa-c1GBe4e+gbGB3FFDg*aFd+cADC-
      schemas: public
      createSchemas: true
      locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

  flyway:
    enabled: true

  springdoc:
    api-docs:
      enable: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui,html