server:
  port: 8080

---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/liquorsgolden
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      schemas: public
      createSchemas: true
      locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

  flyway:
    enabled: true

  message:
    basename: i18n/message

  springdoc:
    api-docs:
      enable: 'true'
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui,html